[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.35"
evm_version = "cancun"
remappings = ["forge-std/=dependencies/forge-std-1.14.0/src/"]

[soldeer]
remappings_generate = false

[dependencies]
forge-std = "1.14.0"
